server:
  port: 9019

spring:
  application:
    name: odm-platform-adapter-marketplace-executor
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: org.opendatamesh.odm.platform.adapter.marketplace.executor.starter.controller

# Logging configuration
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ODM configuration
odm:
  product-plane:
    marketplace-service:
      active: true
      address: http://localhost:8085
  email:
    from: ${ODM_EMAIL_FROM}
    useHtml: ${ODM_EMAIL_USE_HTML:false}
    subscribe-template-path: ${ODM_EMAIL_SUBSCRIBE_TEMPLATE_PATH:classpath:templates/email/subscribe-template.mustache}
    unsubscribe-template-path: ${ODM_EMAIL_UNSUBSCRIBE_TEMPLATE_PATH:classpath:templates/email/unsubscribe-template.mustache}
